using DinoRand.FileFormats.Stage;
using DinoRand.Randomizer;
using DinoRand.Randomizer.Definitions;
using DinoRand.Randomizer.Graph;
using DinoRand.Randomizer.Install;
using DinoRand.Randomizer.Passes;
using Xunit;

namespace DinoRand.FileFormats.Tests;

/// <summary>
/// The DC1 cutscene-safe enemy delivery (STATIC-SCD-RE cont.58/59): the three-tier
/// <see cref="Dc1RoomExclusions"/> census (embedded <c>data/dc1/cutscene-rooms.json</c>,
/// generated by <c>tools/scd_re/cutscene_catalog.py</c>), the option-gated choreography
/// exclusion in the enemy passes, the <see cref="Dc1CutscenePalettePass"/> fallback, and the
/// explicit non-stacking warning primitive (<see cref="GameInstaller.HasPriorEdit"/>, cont.57
/// false-handoff RCA). No game bytes — fixtures are in-memory; one read-only corpus test is
/// env-gated on <c>DINORAND_DC1_DIR</c>.
/// </summary>
public class Dc1CutsceneSafeEnemyTests
{
    // ---- Dc1RoomExclusions: the embedded census ----

    [Fact]
    public void CuratedTiers_MatchTheShippedExclusionLists()
    {
        // Byte-identity guard: these two tiers replaced hardcoded sets in DinoCrisis1 — the JSON
        // must carry exactly the shipped values or default seeds change.
        Assert.Equal(new HashSet<int> { 0x200, 0x202, 0x600, 0x610 }, Dc1RoomExclusions.ScriptedEnemy);
        Assert.Equal(new HashSet<int> { 0x0109, 0x010d, 0x0112, 0x030a, 0x030e }, Dc1RoomExclusions.Cutscene);

        var game = new DinoCrisis1();
        Assert.Equal(Dc1RoomExclusions.ScriptedEnemy, game.ScriptedEnemyRoomCodes);
        Assert.Equal(Dc1RoomExclusions.Cutscene, game.CutsceneRoomCodes);
        Assert.Equal(Dc1RoomExclusions.Choreography, game.ChoreographyRoomCodes);
    }

    [Fact]
    public void Choreography_FlagsTheIntroRaptorRoom_AndSubsumesTheCuratedCutsceneList()
    {
        // 010E hosts the intro raptor ambush choreography (cont.58) — the room that motivated the
        // census — and the derived predicate must independently reproduce every hand-curated
        // cutscene room (convergence check).
        Assert.Contains(0x010e, Dc1RoomExclusions.Choreography);
        Assert.ProperSuperset(Dc1RoomExclusions.Cutscene.ToHashSet(),
                              Dc1RoomExclusions.Choreography.ToHashSet());
        // Plain spawn rooms are NOT flagged (0102 = the CE-lab room, ordinary 0x59 raptor).
        Assert.DoesNotContain(0x0102, Dc1RoomExclusions.Choreography);
    }

    // ---- Enemy permute: option-gated choreography skip ----

    private static int BonesFor(byte category) => category switch
    {
        1 => 15, 2 => 21, 3 => 20, 4 => 10, 5 => 7, 7 => 18, _ => 0,
    };

    private static EnemyRecord Enemy(byte category, uint model, uint motion) => new()
    {
        Category = category,
        ModelPtr = model,
        MotionPtr = motion,
        OriginalModelPtr = model,
        OriginalMotionPtr = motion,
        SpeciesBoneCount = BonesFor(category),
        FileOffset = 0,
    };

    private static RoomFile TwoRaptorRoom(int stage, int room)
    {
        var rf = new RoomFile(stage, room);
        rf.Enemies.Add(Enemy(0x01, 0x80124d28, 0x80146d10));
        rf.Enemies.Add(Enemy(0x01, 0x80128868, 0x80148fb4));
        return rf;
    }

    private static void RunPermute(RoomFile room, bool cutsceneSafe)
    {
        var rooms = new[] { room };
        var ctx = new RandomizationContext(
            new DinoCrisis1(), rooms, RoomGraph.Build(rooms), new Seed(1),
            new RandomizerConfig { Dc1CutsceneSafeEnemies = cutsceneSafe }, _ => { });
        new EnemyRandomizer().Apply(ctx);
    }

    [Fact]
    public void Permute_ChoreographyRoom_OptionOff_IsStillPermuted()
    {
        // Default-off = the shipped behavior byte-identical: 010E is only in the NEW choreography
        // tier (not in the curated cutscene list), so with the option off it keeps permuting.
        var room = TwoRaptorRoom(1, 0x0e);
        RunPermute(room, cutsceneSafe: false);
        Assert.Contains(room.Enemies, e => e.IsEdited);
    }

    [Fact]
    public void Permute_ChoreographyRoom_OptionOn_IsUntouched()
    {
        var room = TwoRaptorRoom(1, 0x0e);
        RunPermute(room, cutsceneSafe: true);
        Assert.All(room.Enemies, e => Assert.False(e.IsEdited));
    }

    [Fact]
    public void Permute_UnflaggedRoom_OptionOn_IsStillPermuted()
    {
        var room = TwoRaptorRoom(1, 0x02); // 0102: plain spawn room, not in any tier
        RunPermute(room, cutsceneSafe: true);
        Assert.Contains(room.Enemies, e => e.IsEdited);
    }

    // ---- Cross-species import: option-gated choreography refusal ----

    private sealed class CountingImporter : ICrossSpeciesImporter
    {
        public readonly List<int> ImportedRooms = new();
        public IReadOnlyCollection<DinoSpecies> AvailableDonors { get; } =
            new[] { DinoSpecies.RaptorHeavy };
        public bool TryImport(RandomizationContext context, RoomFile room, int victimIdx,
                              ExoticSpeciesDef def, out IReadOnlyList<ExePatchRequest> patches, out string note)
        {
            ImportedRooms.Add(room.Stage * 0x100 + room.Room);
            patches = Array.Empty<ExePatchRequest>();
            note = "fake";
            return true;
        }
    }

    private static CountingImporter RunCrossSpecies(RoomFile room, bool cutsceneSafe, int seed)
    {
        var importer = new CountingImporter();
        var rooms = new[] { room };
        var ctx = new RandomizationContext(
            new DinoCrisis1(), rooms, RoomGraph.Build(rooms), new Seed(seed),
            new RandomizerConfig
            {
                CrossRoomEnemySpecies = true,
                EnemyDifficulty = 1.0,
                Dc1CutsceneSafeEnemies = cutsceneSafe,
            }, _ => { });
        new CrossSpeciesEnemyPass(_ => importer).Apply(ctx);
        return importer;
    }

    [Fact]
    public void CrossSpecies_ChoreographyRoom_OptionOn_IsNeverACandidate()
    {
        // The victim shape the pass looks for: a randomizable Velociraptor in a flagged room (010E).
        for (int seed = 1; seed <= 20; seed++)
        {
            var importer = RunCrossSpecies(TwoRaptorRoom(1, 0x0e), cutsceneSafe: true, seed);
            Assert.Empty(importer.ImportedRooms);
        }
    }

    [Fact]
    public void CrossSpecies_ChoreographyRoom_OptionOff_RemainsPlaceable()
    {
        // Control for the test above: with the option off the same fixture IS placeable (proves
        // the refusal comes from the option, not from the fixture never qualifying).
        bool placedAny = false;
        for (int seed = 1; seed <= 20 && !placedAny; seed++)
            placedAny = RunCrossSpecies(TwoRaptorRoom(1, 0x0e), cutsceneSafe: false, seed).ImportedRooms.Count > 0;
        Assert.True(placedAny);
    }

    // ---- Palette-tint fallback pass ----

    [Fact]
    public void PalettePass_GatedOnBothFlags()
    {
        var pass = new Dc1CutscenePalettePass();
        Assert.False(pass.IsEnabled(new RandomizerConfig()));
        Assert.False(pass.IsEnabled(new RandomizerConfig { Dc1CutsceneSafeEnemies = true, RandomizeEnemies = false }));
        Assert.True(pass.IsEnabled(new RandomizerConfig { Dc1CutsceneSafeEnemies = true }));
    }

    [Fact]
    public void PalettePass_RoomWithoutResolvableClut_IsSkippedWithoutCrashing()
    {
        // A flagged room whose RdtBuffer is empty: the CLUT read fails → the pass must skip it
        // (no output override), not throw. Donor-less corpora likewise produce no override.
        var room = TwoRaptorRoom(1, 0x0e);
        var rooms = new[] { room };
        var ctx = new RandomizationContext(
            new DinoCrisis1(), rooms, RoomGraph.Build(rooms), new Seed(1),
            new RandomizerConfig { Dc1CutsceneSafeEnemies = true }, _ => { });

        new Dc1CutscenePalettePass().Apply(ctx);

        Assert.False(ctx.TryGetRoomOutput(room, out _));
    }

    // ---- Non-stacking made explicit (cont.57 false-handoff RCA) ----

    [Fact]
    public void HasPriorEdit_DetectsALiveFileThatDivergesFromItsBackup()
    {
        var dir = Directory.CreateTempSubdirectory("dinorand-stack-test");
        try
        {
            var live = Path.Combine(dir.FullName, "st102.dat");
            File.WriteAllBytes(live, new byte[] { 1, 2, 3, 4 });
            var backup = GameInstaller.BackupOnce(dir.FullName, live);

            // Fresh backup == live: no prior edit.
            Assert.False(GameInstaller.HasPriorEdit(backup, live));

            // First edit applied: the live file now diverges — the next edit REPLACES it and the
            // CLI must say so (room edits rebuild from the pristine backup; they do not stack).
            File.WriteAllBytes(live, new byte[] { 1, 2, 3, 5 });
            Assert.True(GameInstaller.HasPriorEdit(backup, live));

            // Length change is also a divergence.
            File.WriteAllBytes(live, new byte[] { 1, 2, 3 });
            Assert.True(GameInstaller.HasPriorEdit(backup, live));

            // Missing files never report a prior edit.
            Assert.False(GameInstaller.HasPriorEdit(backup + ".nope", live));
        }
        finally { dir.Delete(recursive: true); }
    }

    // ---- Gated read-only corpus test: the tint applies on real rooms ----

    private static string? DataDir()
    {
        var root = Environment.GetEnvironmentVariable("DINORAND_DC1_DIR");
        if (string.IsNullOrEmpty(root)) return null;
        foreach (var c in new[] { root, Path.Combine(root, "Data") })
            if (Directory.Exists(c) && Directory.EnumerateFiles(c, "st*.dat").Any())
                return c;
        return Directory.EnumerateDirectories(root, "Data", SearchOption.AllDirectories).FirstOrDefault();
    }

    /// <summary>Read-only: run the palette pass over real 010E + a donor pool and assert it
    /// produced an output override that differs from the plain serialization only in content
    /// (a palette payload), never in length — the cont.51 in-place 512-byte copy.</summary>
    [Fact]
    public void PalettePass_RealCorpus_TintsTheIntroRaptorRoomInPlace()
    {
        var dir = DataDir();
        if (dir is null) return; // no game files: no-op (CI)

        var files = new[] { "st10e.dat", "st109.dat", "st401.dat", "st511.dat" }
            .Select(f => Path.Combine(dir, f)).Where(File.Exists).ToList();
        if (files.Count < 2) return;

        var rooms = files.Select(p =>
        {
            var name = Path.GetFileNameWithoutExtension(p)[2..];
            int code = Convert.ToInt32(name, 16);
            return RoomFile.Read(code >> 8, code & 0xff, File.ReadAllBytes(p));
        }).ToList();

        var ctx = new RandomizationContext(
            new DinoCrisis1(), rooms, RoomGraph.Build(rooms), new Seed(12345),
            new RandomizerConfig { Dc1CutsceneSafeEnemies = true }, _ => { });
        new Dc1CutscenePalettePass().Apply(ctx);

        var room10e = rooms.First(r => r.Stage == 1 && r.Room == 0x0e);
        Assert.True(ctx.TryGetRoomOutput(room10e, out var tinted));
        var plain = room10e.Write();
        Assert.Equal(plain.Length, tinted.Length); // in-place palette copy — no offset moves
    }
}
