#!/usr/bin/env python3
"""Generate / verify docs/index.md from every doc's YAML frontmatter.

The index is GENERATED — never hand-edit docs/index.md; run this with --apply.

    --apply   (re)write docs/index.md from every corpus:true doc's frontmatter.
    --check   fail (exit 1) if any docs/**/*.md lacks frontmatter, or if
              docs/index.md is stale vs a fresh regeneration (i.e. a corpus doc
              was added/renamed/removed without regenerating). Used by the
              pre-commit hook so the index can never silently drift again.

One line per corpus doc:  `- [title](path) — status · hook`
where title/status come from frontmatter and hook is the doc's first body line.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = os.path.join(ROOT, "docs")
INDEX = os.path.join(DOCS, "index.md")

# Sections, in emit order, keyed by the first path component under docs/.
SECTIONS = [
    ("reference", "Reference — durable validated facts (retrieval-primary)"),
    ("decisions", "Decisions — plans · RCAs · research (point-in-time)"),
    ("parity", "Parity — BioRand / cross-source comparisons"),
    ("runbooks", "Runbooks — reusable operational how-tos"),
]


def parse_frontmatter(text):
    if not text.startswith("---\n"):
        return None, text
    end = text.find("\n---\n", 4)
    if end == -1:
        return None, text
    fm = {}
    for line in text[4:end].splitlines():
        m = re.match(r'([A-Za-z_]+):\s*(.*)$', line)
        if not m:
            continue
        k, v = m.group(1), m.group(2).strip()
        if len(v) >= 2 and v[0] == '"' and v[-1] == '"':
            v = v[1:-1]
        fm[k] = v
    return fm, text[end + 5:]


def hook_of(body):
    lines = body.splitlines()
    i = 0
    while i < len(lines) and not lines[i].strip():
        i += 1
    if i < len(lines) and lines[i].lstrip().startswith("# "):
        i += 1
    while i < len(lines):
        s = lines[i].strip()
        if s and not s.startswith("#") and s != "---":
            return _clean(s)
        i += 1
    return ""


def _clean(s):
    s = re.sub(r'^[>\-\*\s]+', '', s)
    s = re.sub(r'\[([^\]]+)\]\([^)]*\)', r'\1', s)   # markdown links -> text
    s = s.replace("**", "").replace("`", "")
    s = re.sub(r'\s+', ' ', s).strip()
    if len(s) > 140:
        s = s[:139].rstrip() + "…"
    return s


def rel_docs(path):
    return os.path.relpath(path, DOCS).replace(os.sep, "/")


def collect():
    """Return (corpus_docs, missing_frontmatter)."""
    corpus, missing = [], []
    for dirpath, dirnames, filenames in os.walk(DOCS):
        dirnames[:] = [d for d in dirnames if d not in (".git",)]
        for fn in filenames:
            if not fn.endswith(".md"):
                continue
            p = os.path.join(dirpath, fn)
            if os.path.abspath(p) == os.path.abspath(INDEX):
                continue
            with open(p, encoding="utf-8") as fh:
                text = fh.read()
            fm, body = parse_frontmatter(text)
            rel = rel_docs(p)
            if fm is None:
                missing.append(rel)
                continue
            if fm.get("corpus", "").lower() == "true":
                corpus.append({
                    "path": rel,
                    "title": fm.get("title") or fn,
                    "status": fm.get("status", "validated"),
                    "hook": hook_of(body),
                })
    corpus.sort(key=lambda d: d["path"])
    missing.sort()
    return corpus, missing


def render(corpus):
    out = [
        "<!-- GENERATED by scripts/gen_docs_index.py — do not hand-edit; run `python3 scripts/gen_docs_index.py --apply`. -->",
        "",
        "# DinoRand documentation index",
        "",
        "Every corpus doc under `docs/` has exactly one line here, generated from its",
        "frontmatter: `[title](path) — status · hook`. The RE session contract lives in",
        "[CONTRIBUTING-RE.md](CONTRIBUTING-RE.md); acronyms in [glossary.md](glossary.md).",
        "Prompts (`_prompts/`) and verbatim dumps (`_reference-dumps/`) are `corpus:false`",
        "and intentionally excluded.",
        "",
    ]
    seen = set()
    for prefix, heading in SECTIONS:
        rows = [d for d in corpus if d["path"].split("/", 1)[0] == prefix]
        if not rows:
            continue
        out.append(f"## {heading}")
        out.append("")
        for d in rows:
            seen.add(d["path"])
            hook = f" · {d['hook']}" if d["hook"] else ""
            out.append(f"- [{d['title']}]({d['path']}) — {d['status']}{hook}")
        out.append("")
    other = [d for d in corpus if d["path"] not in seen]
    if other:
        out.append("## Other")
        out.append("")
        for d in other:
            hook = f" · {d['hook']}" if d["hook"] else ""
            out.append(f"- [{d['title']}]({d['path']}) — {d['status']}{hook}")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def main():
    mode = sys.argv[1] if len(sys.argv) > 1 else "--check"
    corpus, missing = collect()
    expected = render(corpus)
    if mode == "--apply":
        with open(INDEX, "w", encoding="utf-8") as fh:
            fh.write(expected)
        print(f"gen_docs_index: wrote {rel_docs(INDEX)} ({len(corpus)} corpus docs)")
        if missing:
            print("gen_docs_index: WARNING — docs missing frontmatter:", file=sys.stderr)
            for m in missing:
                print(f"  - docs/{m}", file=sys.stderr)
        return 0
    # --check
    ok = True
    if missing:
        ok = False
        print("gen_docs_index: these docs/ files lack YAML frontmatter:", file=sys.stderr)
        for m in missing:
            print(f"  - docs/{m}", file=sys.stderr)
    current = ""
    if os.path.exists(INDEX):
        with open(INDEX, encoding="utf-8") as fh:
            current = fh.read()
    if current != expected:
        ok = False
        print("gen_docs_index: docs/index.md is stale — run "
              "'python3 scripts/gen_docs_index.py --apply'", file=sys.stderr)
    if not ok:
        return 1
    print("gen_docs_index: OK")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
