#!/usr/bin/env python3
"""Generate / verify the committed vanilla-reachability docs (DOCS-AUDIENCE-PLAN.md §5a).

Renders the *distilled logic model* (the same model the Archipelago apworlds run, built by
scripts/gen_ap_logic.py from the authored data/ JSON — no game files, no install) into two
human-checkable Markdown pages:

    docs/reference/dc1/generated/REACHABILITY.md
    docs/reference/dc2/generated/REACHABILITY.md

Each page shows the sphere/wave progression order (the Archipelago/OoTR spoiler-playthrough
convention: sphere 0 = reachable empty-handed; sphere N opens with what spheres < N granted)
plus a Mermaid rendering of the graph the model actually uses. Engine-truth spheres for a
concrete seed live in the per-seed SPOILER.md ("Playthrough (DC1 spheres)" section) — this
page is the *vanilla contract* view, kept fresh by --check like every other generator.

    --apply   (re)write both docs.
    --check   re-derive and assert the logic invariants; byte-compare against the files on
              disk when they exist (docs/ is publish-held-back, so a CI checkout has no
              docs/ tree — there --check degrades to the invariant asserts alone).

Fidelity caveats rendered into the DC1 page (do not silently widen them):
  * star topology — the distilled model frees every room that is not a gated-edge target;
    full door connectivity lives only in the .dat door records (engine RoomGraph).
  * progression items without a distilled pickup location (event-granted, e.g. keys granted
    by triggers rather than item_control records) are assumed held from the start, flagged.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_ap_logic as ap  # noqa: E402  (sibling script; shared distiller + flood-fill)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = {
    "dc1": os.path.join(ROOT, "docs", "reference", "dc1", "generated", "REACHABILITY.md"),
    "dc2": os.path.join(ROOT, "docs", "reference", "dc2", "generated", "REACHABILITY.md"),
}
GENERATED_BANNER = ("**Status:** GENERATED by `scripts/gen_reachability.py` — do not hand-edit; "
                    "run `python3 scripts/gen_reachability.py --apply`.")


def _frontmatter(title: str, slug: str, game: str) -> str:
    return (f'---\ntitle: "{title}"\nslug: {slug}\ngame: {game}\nsubsystem: logic\n'
            f"doc_type: reference\nstatus: validated\ncorpus: true\nconfidence: open\n"
            f"chunk: default\nrelated: []\n---\n")


def _spheres(data: dict, held: set, locs_by_item: dict) -> list[dict]:
    """Sphere fixpoint over the distilled model, mirroring KeyItemPlacer.Verify's recording rule:
    every productive round, the baseline round, and the terminal round after progress."""
    taken: set = set()
    spheres: list[dict] = []
    while True:
        reach = ap._reachable_rooms(data, held)
        got = []
        for iid, rooms in sorted(locs_by_item.items()):
            if iid in taken or iid in held:
                continue
            room = next((r for r in rooms if r in reach), None)
            if room is not None:
                got.append((iid, room))
        if got or not spheres or spheres[-1]["collected"]:
            spheres.append({"index": len(spheres), "rooms": len(reach),
                            "reach": reach, "collected": got})
        if not got:
            return spheres
        for iid, _ in got:
            taken.add(iid)
            held.add(iid)


def build_dc1_doc() -> tuple[str, dict]:
    data = ap.build_dc1()
    names = {int(k): v for k, v in data["items"]["names"].items()}
    prog = data["items"]["progressionItemIds"]
    regions = data["regions"]

    locs_by_item: dict[int, list[str]] = {}
    for loc in data["locations"]:
        if loc["itemId"] in prog:
            locs_by_item.setdefault(loc["itemId"], []).append(loc["room"])
    unmodeled = sorted(i for i in prog if i not in locs_by_item)

    spheres = _spheres(data, set(unmodeled), locs_by_item)
    final_reach = spheres[-1]["reach"]
    assert data["goalRoom"] in final_reach, "DC1 vanilla goal unreachable in distilled model"

    gated = [e for e in data["edges"] if e["requiresItems"] or e["requiresRooms"]]

    def room(c: str) -> str:
        n = regions.get(c, c)
        return c if n == c else f"{c} ({n})"

    lines = [
        _frontmatter("DC1 vanilla reachability — sphere order (generated)",
                     "dc1-reachability-generated", "dc1"),
        "# DC1 vanilla reachability — sphere order",
        "",
        GENERATED_BANNER,
        "",
        "Source model: the **distilled logic** the DC1 apworld runs "
        "(`scripts/gen_ap_logic.py` over authored `data/dc1/{map,items,room-data}.json`) — "
        "star topology plus the gated-edge overlay. It is NOT the engine door graph: "
        "engine-truth spheres for a seed are in that seed's `SPOILER.md`.",
        "",
        f"Start `{room(data['startRoom'])}` → goal `{room(data['goalRoom'])}`. "
        f"Progression items: {', '.join(f'`{names[i]}`' for i in prog)}.",
    ]
    if unmodeled:
        lines += [
            "",
            "> ⚠ **Event-granted keys (no distilled pickup location):** "
            + ", ".join(f"`{names[i]}`" for i in unmodeled)
            + " — granted by script triggers, not `item_control` records, so the distilled model "
              "assumes them held from the start. The engine model (per-seed spoiler) tracks their "
              "real acquisition.",
        ]
    lines += ["", "## Sphere playthrough (vanilla layout)", "",
              "| Sphere | Rooms reachable | Progression collected in this sphere |",
              "|---|---|---|"]
    for s in spheres:
        got = "; ".join(f"{names[i]} @ {room(r)}" for i, r in s["collected"]) or "—"
        lines.append(f"| {s['index']} | {s['rooms']} / {len(regions)} | {got} |")
    lines += ["", f"Goal `{room(data['goalRoom'])}` reachable after {len(spheres)} sphere(s).",
              "", "## Gated edges (the logic overlay)", "",
              "| From | To | Needs item(s) | Needs visit |", "|---|---|---|---|"]
    for e in gated:
        items = ", ".join(names[i] for i in e["requiresItems"]) or "—"
        visits = ", ".join(room(r) for r in e["requiresRooms"]) or "—"
        lines.append(f"| {room(e['from'])} | {room(e['to'])} | {items} | {visits} |")
    lines += [
        "", "## Gate-overlay graph", "",
        "Only the gated edges are drawn — in the star model every other room is freely "
        "reachable. A full DC1 room-connectivity diagram needs the door-record export "
        "(future increment, DOCS-AUDIENCE-PLAN.md §5a deviations).",
        "", "```mermaid", "graph LR",
    ]
    for e in gated:
        label = ", ".join(names[i] for i in e["requiresItems"])
        label = " + ".join(x for x in [label, ("visit " + ", ".join(e["requiresRooms"])
                                               if e["requiresRooms"] else "")] if x)
        lines.append(f'    r{e["from"]}["{room(e["from"])}"] -->|{label}| r{e["to"]}["{room(e["to"])}"]')
    lines += ["```", ""]
    return "\n".join(lines), data


def _dc2_waves(data: dict) -> list[list[str]]:
    """Visit-gate cascade: wave 0 = every non-gated-target room; wave N = rooms whose edge opens
    once waves < N are reachable. Mirrors ap._reachable_rooms iteration-by-iteration (asserted)."""
    gated_targets = {e["to"] for e in data["edges"]}
    reach = {c for c in data["regions"] if c not in gated_targets}
    waves = [sorted(reach)]
    while True:
        opened = []
        for e in data["edges"]:
            if e["to"] in reach or e["from"] not in reach:
                continue
            if not e["requiresItems"] and all(r in reach for r in e["requiresRooms"]):
                opened.append(e["to"])
        if not opened:
            break
        reach.update(opened)
        waves.append(sorted(set(opened)))
    assert reach == ap._reachable_rooms(data, set()), "wave cascade diverged from the checker model"
    return waves


def build_dc2_doc() -> tuple[str, dict]:
    data = ap.build_dc2()
    waves = _dc2_waves(data)
    all_reach = {r for w in waves for r in w}
    assert data["goalRoom"] in all_reach, "DC2 goal unreachable in distilled model"

    lines = [
        _frontmatter("DC2 vanilla reachability — visit-gate waves + door graph (generated)",
                     "dc2-reachability-generated", "dc2"),
        "# DC2 vanilla reachability — visit-gate waves + door graph",
        "",
        GENERATED_BANNER,
        "",
        "Source model: the **distilled logic** the DC2 apworld runs (v1 contract: visit-gated, "
        "no key-item shuffle — the op-0x31 item lever is still unverified, K77). Wave 0 is every "
        "room the star model frees; each later wave lists rooms whose gate opens once the "
        "earlier waves are reachable. Door topology below is the K81 decode "
        "(`data/dc2/door-graph.json`).",
        "", "## Visit-gate cascade (vanilla)", "",
        "| Wave | Rooms opened |", "|---|---|",
    ]
    for i, w in enumerate(waves):
        rooms = f"{len(w)} rooms (star-free)" if i == 0 else ", ".join(f"ST{r}" for r in w)
        lines.append(f"| {i} | {rooms} |")
    lines += ["", f"Goal ST{data['goalRoom']} reachable; "
              f"{len(all_reach)}/{len(data['regions'])} rooms in the playable set.",
              "", "## Door graph (K81 decode) — per stage", ""]

    graph = ap.json.loads((ap.DC2 / "door-graph.json").read_text(encoding="utf-8"))
    edges: set[tuple[str, str]] = set()
    for src, rec in graph["rooms"].items():
        for d in rec.get("doors", []):
            dest = d.get("dest_id")
            if dest:
                edges.add((src, dest))
    stages = sorted({r[0] for r in graph["rooms"]})
    for st in stages:
        lines += [f"### Stage {st}xx", "", "```mermaid", "graph LR"]
        drawn: set[frozenset] = set()
        for a, b in sorted(edges):
            if a[0] != st and b[0] != st:
                continue
            pair = frozenset((a, b))
            if pair in drawn:
                continue
            if (b, a) in edges and a != b:
                drawn.add(pair)
                lines.append(f"    s{a}[ST{a}] --- s{b}[ST{b}]")
            else:
                drawn.add(pair)
                lines.append(f"    s{a}[ST{a}] --> s{b}[ST{b}]")
        lines += ["```", ""]
    lines += ["One-way arrows are doors with no decoded return door — review them as "
              "potential no-return transitions.", ""]
    return "\n".join(lines), data


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument("--apply", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = p.parse_args()

    docs = {"dc1": build_dc1_doc(), "dc2": build_dc2_doc()}
    # Reuse the distiller's own invariants so this generator can never pass on a broken model.
    ap.check_dc1(docs["dc1"][1])
    ap.check_dc2(docs["dc2"][1])

    rc = 0
    for game, (text, _) in docs.items():
        path = OUT[game]
        if args.apply:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
            print(f"gen_reachability: wrote {os.path.relpath(path, ROOT)}")
        elif not os.path.exists(path):
            # docs/ is held back from publish — a CI checkout has no docs tree. The logic
            # invariants above already ran; nothing on disk to compare.
            print(f"gen_reachability: {os.path.relpath(path, ROOT)} absent (CI checkout?) — "
                  "invariants OK, byte-compare skipped")
        elif open(path, encoding="utf-8").read() != text:
            print(f"gen_reachability: STALE {os.path.relpath(path, ROOT)} — run --apply",
                  file=sys.stderr)
            rc = 1
        else:
            print(f"gen_reachability: OK {os.path.relpath(path, ROOT)}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
