#!/usr/bin/env python3
"""Generate / verify the committed DATA-REFERENCE docs (DOCS-AUDIENCE-PLAN.md §5/§6.4).

Human-readable tables rendered from the authored `data/dc1|dc2/*.json` catalogs — items,
enemies, rooms, vanilla pickup locations — so the lists modders and players ask for exist
in readable form without anyone hand-maintaining them (the OoTR location-DB drift
anti-pattern). The JSON stays canonical; these pages are views.

    docs/reference/dc1/generated/DATA-REFERENCE.md
    docs/reference/dc2/generated/DATA-REFERENCE.md

    --apply   (re)write both docs.
    --check   re-derive; byte-compare against the files on disk when they exist
              (docs/ is publish-held-back, so a CI checkout has no docs/ tree —
              there --check degrades to "generation succeeds").

DMCA scope: renders ONLY what is already committed and published under data/ (authored /
own-decode JSON). Never add a table sourced from the registries or the executables here.
"""
import argparse
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_ap_logic as ap  # noqa: E402  (DC1 vanilla pickup locations come from the distiller)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA1 = os.path.join(ROOT, "data", "dc1")
DATA2 = os.path.join(ROOT, "data", "dc2")
OUT = {
    "dc1": os.path.join(ROOT, "docs", "reference", "dc1", "generated", "DATA-REFERENCE.md"),
    "dc2": os.path.join(ROOT, "docs", "reference", "dc2", "generated", "DATA-REFERENCE.md"),
}
GENERATED_BANNER = ("**Status:** GENERATED by `scripts/gen_data_reference.py` — do not hand-edit; "
                    "run `python3 scripts/gen_data_reference.py --apply`.")


def _load(base, name):
    with open(os.path.join(base, name), encoding="utf-8") as fh:
        return json.load(fh)


def _cell(v, cap=160):
    s = "—" if v in (None, "", []) else str(v)
    s = s.replace("\n", " ").replace("|", "\\|")
    return s if len(s) <= cap else s[: cap - 1].rstrip() + "…"


def _table(headers, rows):
    out = ["| " + " | ".join(headers) + " |", "|" + "---|" * len(headers)]
    out += ["| " + " | ".join(_cell(c) for c in r) + " |" for r in rows]
    return out


def _frontmatter(title, slug, game):
    return (f'---\ntitle: "{title}"\nslug: {slug}\ngame: {game}\nsubsystem: data\n'
            f"doc_type: reference\nstatus: validated\ncorpus: true\nconfidence: open\n"
            f"chunk: default\nrelated: []\n---\n")


def build_dc1_doc():
    items = _load(DATA1, "items.json")
    species = _load(DATA1, "enemies.json")["species"]
    room_data = _load(DATA1, "room-data.json")["rooms"]
    locs = ap.load_locations(ap.load_items()["names"])  # full row set incl. runtime-armed slots

    lines = [_frontmatter("DC1 data reference — items, enemies, rooms, pickups (generated)",
                          "dc1-data-reference-generated", "dc1"),
             "# DC1 data reference — items, enemies, rooms, pickups",
             "", GENERATED_BANNER, "",
             "Rendered from the authored `data/dc1/*.json` (provenance in "
             "[data/dc1/README.md](../../../../data/dc1/README.md)); the JSON is canonical.", ""]

    lines += ["## Items", ""]
    lines += _table(["Id", "Name", "Category"],
                    [(e["id"], e["name"], e.get("category", "—")) for e in items["allItems"]])
    lines += ["", "## Key items", ""]
    lines += _table(["Id", "Name"], [(e["id"], e["name"]) for e in items["keyItems"]])
    lines += ["", "## Randomizer item pool (base weights)", ""]
    lines += _table(["Id", "Name", "Weight"],
                    [(e["id"], e["name"], e["weight"]) for e in items["pool"]])

    lines += ["", "## Enemy species (model classes)", ""]
    lines += _table(["Class", "Bones", "Name", "Confidence", "Note"],
                    [(s["id"], s["bones"], s["name"], s.get("confidence", "—"),
                      s.get("note", "—")) for s in species])
    lines += ["", "Per-room enemy placements live in the room files (decoded at run time), "
              "not in committed data — see the per-seed `SPOILER.md` for a concrete layout.", ""]

    lines += ["## Vanilla pickup locations", "",
              "One row per logical pickup (`item_control` record; relocation twins collapsed). "
              "Coordinates are the placement quad's first corner. Source: `static` = placed at "
              "room load; `runtime-armed (trigger)` = slot whose item id a trigger/native code "
              "sets at runtime (id unknowable statically; gating flag shown when decoded); "
              "`event-granted` = placed by a non-load event subroutine. Emergency-box contents "
              "(`emergency-boxes.json`) and keys granted with no placement record are separate "
              "systems, not rows here.", ""]
    lines += _table(["Room", "Room name", "Item id", "Item", "X,Z", "Source"],
                    [(l["room"], l["name"].split(" (")[0], f"0x{l['itemId']:02x}",
                      l["itemName"], f"{l['pos'][0]},{l['pos'][1]}",
                      l["source"] + (f" gate {l['gateFlag']}" if l.get("gateFlag") else ""))
                     for l in locs])

    rooms = sorted(room_data.items())
    lines += ["", "## Rooms", ""]
    lines += _table(["Code", "Name", "Pickup records"],
                    [(code, r.get("name", "—"),
                      len((r.get("item_control") or {}).get("records", [])))
                     for code, r in rooms])
    lines += ["", "BGM mood manifest (`data/dc1/bgm.json`): v1 ships empty mood arrays — "
              "track→mood curation is future data.", ""]
    return "\n".join(lines)


def build_dc2_doc():
    items = _load(DATA2, "items.json")
    enemies = _load(DATA2, "enemies.json")
    rooms = _load(DATA2, "rooms.json")["rooms"]
    epr = _load(DATA2, "enemies-per-room.json")["rooms"]

    lines = [_frontmatter("DC2 data reference — items, enemies, rooms (generated)",
                          "dc2-data-reference-generated", "dc2"),
             "# DC2 data reference — items, enemies, rooms",
             "", GENERATED_BANNER, "",
             "Rendered from the authored `data/dc2/*.json` (provenance in "
             "[data/dc2/README.md](../../../../data/dc2/README.md) and "
             "[sources.md](../../../../data/dc2/sources.md)); the JSON is canonical.", ""]

    lines += ["## Item catalog", ""]
    lines += _table(["Id", "Name", "Category"],
                    [(e["id"], e["name"], e.get("category", "—")) for e in items["catalog"]])
    lines += ["", f"Key item ids: {', '.join(items['keyItemIds'])}.", ""]

    ft = items.get("_field_pickup_types", {}).get("types", {})
    if ft:
        lines += ["## Field-pickup types (op-0x31 id space — separate from the catalog; "
                  "item lever unverified, K77)", ""]
        lines += _table(["Type", "Meaning"], sorted(ft.items(), key=lambda kv: int(kv[0])))
        lines += [""]

    lines += ["## Enemy roster", ""]
    lines += _table(["Creature", "Size", "Role", "Model files", "Provenance"],
                    [(r["name"], r.get("size", "—"), r.get("role", "—"),
                      r.get("files_hyp", "—"), r.get("provenance", "—"))
                     for r in enemies["roster"]])
    lines += ["", "## Raptor colour/HP variants", ""]
    lines += _table(["Variant", "Tier", "HP (normal)", "Where"],
                    [(v["name"], v.get("tier", "—"), v.get("hp_normal", "—"),
                      v.get("spawn", "—")) for v in enemies["raptorVariants"]])
    lines += ["", "## Enemy model slots (E*.DAT)", ""]
    lines += _table(["Slot", "Creature", "Confidence", "Objects", "Tris", "Quads"],
                    [(m["slot"], m.get("creature_guess", "—"),
                      m.get("creature_confidence", "—"), m.get("obj_cnt", "—"),
                      m.get("tri_cnt", "—"), m.get("quad_cnt", "—"))
                     for m in enemies["models"]])

    lines += ["", "## Rooms (ST*.DAT)", ""]
    lines += _table(["Id", "Name", "Zone"],
                    [(r["id"], r.get("name"), r.get("zone", "—")) for r in rooms])
    lines += ["", "## Runtime-witnessed per-room enemy sets (partial census)", ""]
    lines += _table(["Room", "E-files loaded", "Confidence"],
                    [(code, ", ".join(v.get("enemies", [])) or "—",
                      v.get("confidence", "—")) for code, v in sorted(epr.items())])
    lines += ["", "This census is runtime-witnessed and partial by design "
              "(`data/dc2/enemies-per-room.json` — DC2 has no spawn table in the room file); "
              "wave-descriptor data lives in `data/dc2/wave-descriptors.json`.", ""]
    return "\n".join(lines)


def main():
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument("--apply", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = p.parse_args()

    docs = {"dc1": build_dc1_doc(), "dc2": build_dc2_doc()}
    rc = 0
    for game, text in docs.items():
        path = OUT[game]
        if args.apply:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as fh:
                fh.write(text)
            print(f"gen_data_reference: wrote {os.path.relpath(path, ROOT)}")
        elif not os.path.exists(path):
            print(f"gen_data_reference: {os.path.relpath(path, ROOT)} absent (CI checkout?) — "
                  "generation OK, byte-compare skipped")
        elif open(path, encoding="utf-8").read() != text:
            print(f"gen_data_reference: STALE {os.path.relpath(path, ROOT)} — run --apply",
                  file=sys.stderr)
            rc = 1
        else:
            print(f"gen_data_reference: OK {os.path.relpath(path, ROOT)}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
