#!/usr/bin/env python3
"""Generate / verify the committed vanilla-reachability docs (DOCS-AUDIENCE-PLAN.md §5a).

Renders the *distilled logic model* (the same model the Archipelago apworlds run, built by
scripts/gen_ap_logic.py from the authored data/ JSON — no game files, no install) into two
human-checkable Markdown pages:

    docs/reference/dc1/generated/REACHABILITY.md
    docs/reference/dc2/generated/REACHABILITY.md

Each page shows the sphere/wave progression order (the Archipelago/OoTR spoiler-playthrough
convention: sphere 0 = reachable empty-handed; sphere N opens with what spheres < N granted)
plus a Mermaid rendering of the graph the model actually uses. Engine-truth spheres for a
concrete seed live in the per-seed SPOILER.md ("Playthrough (DC1 spheres)" section) — this
page is the *vanilla contract* view, kept fresh by --check like every other generator.

    --apply   (re)write both docs.
    --check   re-derive and assert the logic invariants; byte-compare against the files on
              disk when they exist (docs/ is publish-held-back, so a CI checkout has no
              docs/ tree — there --check degrades to the invariant asserts alone).

Fidelity caveats rendered into the DC1 page (do not silently widen them):
  * star topology — the distilled model frees every room that is not a gated-edge target;
    full door connectivity lives only in the .dat door records (engine RoomGraph).
  * progression items without a distilled pickup location (event-granted, e.g. keys granted
    by triggers rather than item_control records) are assumed held from the start, flagged.
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_ap_logic as ap  # noqa: E402  (sibling script; shared distiller + flood-fill)

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = {
    "dc1": os.path.join(ROOT, "docs", "reference", "dc1", "generated", "REACHABILITY.md"),
    "dc2": os.path.join(ROOT, "docs", "reference", "dc2", "generated", "REACHABILITY.md"),
}
GENERATED_BANNER = ("**Status:** GENERATED by `scripts/gen_reachability.py` — do not hand-edit; "
                    "run `python3 scripts/gen_reachability.py --apply`.")


def _frontmatter(title: str, slug: str, game: str) -> str:
    return (f'---\ntitle: "{title}"\nslug: {slug}\ngame: {game}\nsubsystem: logic\n'
            f"doc_type: reference\nstatus: validated\ncorpus: true\nconfidence: open\n"
            f"chunk: default\nrelated: []\n---\n")


def _spheres(data: dict, held: set, locs_by_item: dict) -> list[dict]:
    """Sphere fixpoint over the distilled model, mirroring KeyItemPlacer.Verify's recording rule:
    every productive round, the baseline round, and the terminal round after progress."""
    taken: set = set()
    spheres: list[dict] = []
    while True:
        reach = ap._reachable_rooms(data, held)
        got = []
        for iid, rooms in sorted(locs_by_item.items()):
            if iid in taken or iid in held:
                continue
            room = next((r for r in rooms if r in reach), None)
            if room is not None:
                got.append((iid, room))
        if got or not spheres or spheres[-1]["collected"]:
            spheres.append({"index": len(spheres), "rooms": len(reach),
                            "reach": reach, "collected": got})
        if not got:
            return spheres
        for iid, _ in got:
            taken.add(iid)
            held.add(iid)


def build_dc1_doc() -> tuple[str, dict]:
    data = ap.build_dc1()
    names = {int(k): v for k, v in data["items"]["names"].items()}
    prog = data["items"]["progressionItemIds"]
    regions = data["regions"]

    locs_by_item: dict[int, list[str]] = {}
    for loc in data["locations"]:
        if loc["itemId"] in prog:
            locs_by_item.setdefault(loc["itemId"], []).append(loc["room"])
    unmodeled = sorted(i for i in prog if i not in locs_by_item)

    spheres = _spheres(data, set(unmodeled), locs_by_item)
    final_reach = spheres[-1]["reach"]
    assert data["goalRoom"] in final_reach, "DC1 vanilla goal unreachable in distilled model"

    gated = [e for e in data["edges"] if e["requiresItems"] or e["requiresRooms"]]

    def room(c: str) -> str:
        n = regions.get(c, c)
        return c if n == c else f"{c} ({n})"

    lines = [
        _frontmatter("DC1 vanilla reachability — sphere order (generated)",
                     "dc1-reachability-generated", "dc1"),
        "# DC1 vanilla reachability — sphere order",
        "",
        GENERATED_BANNER,
        "",
        "Source model: the **distilled logic** the DC1 apworld runs "
        "(`scripts/gen_ap_logic.py` over authored `data/dc1/{map,items,room-data}.json`) — "
        "star topology plus the gated-edge overlay. It is NOT the engine door graph: "
        "engine-truth spheres for a seed are in that seed's `SPOILER.md`.",
        "",
        f"Start `{room(data['startRoom'])}` → goal `{room(data['goalRoom'])}`. "
        f"Progression items: {', '.join(f'`{names[i]}`' for i in prog)}.",
    ]
    if unmodeled:
        lines += [
            "",
            "> ⚠ **Event-granted keys (no distilled pickup location):** "
            + ", ".join(f"`{names[i]}`" for i in unmodeled)
            + " — granted by script triggers, not `item_control` records, so the distilled model "
              "assumes them held from the start. The engine model (per-seed spoiler) tracks their "
              "real acquisition.",
        ]
    lines += ["", "## Sphere playthrough (vanilla layout)", "",
              "| Sphere | Rooms reachable | Progression collected in this sphere |",
              "|---|---|---|"]
    for s in spheres:
        got = "; ".join(f"{names[i]} @ {room(r)}" for i, r in s["collected"]) or "—"
        lines.append(f"| {s['index']} | {s['rooms']} / {len(regions)} | {got} |")
    lines += ["", f"Goal `{room(data['goalRoom'])}` reachable after {len(spheres)} sphere(s).",
              "", "## Gated edges (the logic overlay)", "",
              "| From | To | Needs item(s) | Needs visit |", "|---|---|---|---|"]
    for e in gated:
        items = ", ".join(names[i] for i in e["requiresItems"]) or "—"
        visits = ", ".join(room(r) for r in e["requiresRooms"]) or "—"
        lines.append(f"| {room(e['from'])} | {room(e['to'])} | {items} | {visits} |")
    lines += [
        "", "## Gate-overlay graph", "",
        "Only the gated edges are drawn — in the star model every other room is freely "
        "reachable. A full DC1 room-connectivity diagram needs the door-record export "
        "(future increment, DOCS-AUDIENCE-PLAN.md §5a deviations).",
        "", "```mermaid", "graph LR",
    ]
    for e in gated:
        label = ", ".join(names[i] for i in e["requiresItems"])
        label = " + ".join(x for x in [label, ("visit " + ", ".join(e["requiresRooms"])
                                               if e["requiresRooms"] else "")] if x)
        lines.append(f'    r{e["from"]}["{room(e["from"])}"] -->|{label}| r{e["to"]}["{room(e["to"])}"]')
    lines += ["```", ""]
    return "\n".join(lines), data


def _dc2_spheres(data: dict) -> list[dict]:
    """Collect reachable vanilla progression sources over the physical room graph."""
    progression = set(data["items"]["progressionItemIds"])
    held: set[int] = set()
    collected: set[str] = set()
    spheres: list[dict] = []
    while True:
        reach = ap._reachable_rooms(data, held)
        available = []
        for location in data["locations"]:
            if location["sourceId"] in collected or location["itemId"] not in progression:
                continue
            if (
                location["room"] in reach
                and set(location["requiresItems"]).issubset(held)
                and set(location["requiresRooms"]).issubset(reach)
            ):
                available.append(location)
        if available or not spheres or spheres[-1]["collected"]:
            spheres.append({"index": len(spheres), "reach": reach, "collected": available})
        if not available:
            return spheres
        for location in available:
            collected.add(location["sourceId"])
            held.add(location["itemId"])


def build_dc2_doc() -> tuple[str, dict]:
    data = ap.build_dc2()
    names = {int(key): value for key, value in data["items"]["names"].items()}
    spheres = _dc2_spheres(data)
    final_reach = spheres[-1]["reach"]
    assert data["goalRoom"] in final_reach, "DC2 goal unreachable in vanilla physical model"
    assert len(final_reach) == len(data["regions"]), "supported DC2 graph is not fully reachable"
    gated = [edge for edge in data["edges"] if edge["requiresItems"] or edge["requiresRooms"]]

    lines = [
        _frontmatter("DC2 vanilla reachability - item spheres + physical graph (generated)",
                     "dc2-reachability-generated", "dc2"),
        "# DC2 vanilla reachability - item spheres + physical graph",
        "",
        GENERATED_BANNER,
        "",
        "Source model: the **v2 physical-room contract** the DC2 apworld runs, distilled from "
        "byte-provenanced item sources, door commits, door guards, and the item catalog. "
        "SAT-1/op-`0x31` triggers are excluded from item placement; only sources explicitly "
        "classified as AP-available enter the 42-location pool.",
        "",
        f"Start `ST{data['startRoom']}`; guarded victory transition "
        f"`ST{data['victory']['from']}->ST{data['victory']['to']}`; goal "
        f"`ST{data['goalRoom']}`.",
        "", "## Vanilla progression spheres", "",
        "| Sphere | Rooms reachable | Progression collected |", "|---|---|---|",
    ]
    for sphere in spheres:
        collected = "; ".join(
            f"{names[location['itemId']]} @ ST{location['room']}"
            for location in sphere["collected"]
        ) or "-"
        lines.append(
            f"| {sphere['index']} | {len(sphere['reach'])} / {len(data['regions'])} | "
            f"{collected} |"
        )
    lines += [
        "",
        f"Goal `ST{data['goalRoom']}` and all {len(data['regions'])} supported rooms are "
        "reachable after the vanilla Gas Mask source is collected.",
        "", "## Modeled progression and visit gates", "",
        "| From | To | Needs item(s) | Needs visit | Disposition |",
        "|---|---|---|---|---|",
    ]
    for edge in gated:
        items = ", ".join(names[item_id] for item_id in edge["requiresItems"]) or "-"
        visits = ", ".join(f"ST{room}" for room in edge["requiresRooms"]) or "-"
        lines.append(
            f"| ST{edge['from']} | ST{edge['to']} | {items} | {visits} | "
            f"`{edge['disposition']}` |"
        )

    lines += ["", "## Supported physical door graph - per stage", ""]
    stages = sorted({room[0] for room in data["regions"]})
    for stage in stages:
        lines += [f"### Stage {stage}xx", "", "```mermaid", "graph LR"]
        for edge in data["edges"]:
            source, target = edge["from"], edge["to"]
            if source[0] != stage and target[0] != stage:
                continue
            requirements = ", ".join(names[item_id] for item_id in edge["requiresItems"])
            if edge["requiresRooms"]:
                visit = "visit " + ", ".join(f"ST{room}" for room in edge["requiresRooms"])
                requirements = " + ".join(part for part in (requirements, visit) if part)
            arrow = f"-->|{requirements}|" if requirements else "-->"
            lines.append(f"    s{source}[ST{source}] {arrow} s{target}[ST{target}]")
        lines += ["```", ""]
    lines += [
        "The graph contains only the 85 supported physical rooms. Character-lockout rooms "
        "ST608/ST707 and no-start-site rooms ST905/ST906 are excluded by the v2 contract.", ""
    ]
    return "\n".join(lines), data


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    mode = p.add_mutually_exclusive_group(required=True)
    mode.add_argument("--apply", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = p.parse_args()

    docs = {"dc1": build_dc1_doc(), "dc2": build_dc2_doc()}
    # Reuse the distiller's own invariants so this generator can never pass on a broken model.
    ap.check_dc1(docs["dc1"][1])
    ap.check_dc2(docs["dc2"][1])

    rc = 0
    for game, (text, _) in docs.items():
        path = OUT[game]
        if args.apply:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(text)
            print(f"gen_reachability: wrote {os.path.relpath(path, ROOT)}")
        elif not os.path.exists(path):
            # docs/ is held back from publish — a CI checkout has no docs tree. The logic
            # invariants above already ran; nothing on disk to compare.
            print(f"gen_reachability: {os.path.relpath(path, ROOT)} absent (CI checkout?) — "
                  "invariants OK, byte-compare skipped")
        elif open(path, encoding="utf-8").read() != text:
            print(f"gen_reachability: STALE {os.path.relpath(path, ROOT)} — run --apply",
                  file=sys.stderr)
            rc = 1
        else:
            print(f"gen_reachability: OK {os.path.relpath(path, ROOT)}")
    return rc


if __name__ == "__main__":
    sys.exit(main())
